workflows:
  ios_capacitor_appstore:
    name: iOS Capacitor App Store (nested app dir)
    max_build_duration: 60
    environment:
      xcode: 16.4
      node: 22
      cocoapods: default
      vars:
        APP_DIR: "TeacherType"
        XCODE_SCHEME: "App"
        XCODE_WORKSPACE: "TeacherType/ios/App/App.xcworkspace"
        DEVELOPMENT_TEAM: "8598VNYD3C"
    scripts:
      - name: Install dependencies
        script: |
          cd "$APP_DIR"
          npm ci
      - name: Build web and sync Capacitor
        script: |
          cd "$APP_DIR"
          npm run build
          npx cap sync ios
      - name: CocoaPods
        script: |
          cd "$APP_DIR/ios/App"
          pod repo update
          pod install
      - name: Xcode archive
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -destination "generic/platform=iOS" \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            CODE_SIGN_STYLE=Automatic \
            -allowProvisioningUpdates \
            archive
      - name: Create exportOptions.plist
        script: |
          cat > "$CM_BUILD_DIR/exportOptions.plist" <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>automatic</string>
            <key>uploadSymbols</key><true/>
            <key>stripSwiftSymbols</key><true/>
            <key>compileBitcode</key><false/>
          </dict>
          </plist>
          PLIST
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -exportPath "$CM_BUILD_DIR/build" \
            -exportOptionsPlist "$CM_BUILD_DIR/exportOptions.plist" \
            -allowProvisioningUpdates
    artifacts:
      - build/*.ipa
      - App.xcarchive
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_app_store: false
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
