workflows:
  ios_auto_sign:
    name: "iOS • Auto signing via ASC"
    environment:
      xcode: 16.4
      cocoapods: default
      groups:
        - appstore     # must contain: APP_STORE_CONNECT_PRIVATE_KEY_B64, CERTIFICATE_PRIVATE_KEY_B64, APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER
      vars:
        BUNDLE_ID: "com.your.real.bundleid"    # <-- set this to your app's bundle id
        XCODE_PROJECT: "YourApp.xcworkspace"   # or "YourApp.xcodeproj" if you DON'T use CocoaPods
        XCODE_SCHEME: "YourScheme"             # shared scheme name
        EXPORT_METHOD: "app-store"             # app-store | ad-hoc | development | enterprise

    cache:
      cache_paths:
        - "~/Library/Caches/CocoaPods"
        - "~/Library/Developer/Xcode/DerivedData"

    scripts:
      - name: "Decode keys (normalize) + fetch signing files"
        script: |
          set -euo pipefail

          # ---- required env from group: appstore ----
          : "${APP_STORE_CONNECT_PRIVATE_KEY_B64:?missing APP_STORE_CONNECT_PRIVATE_KEY_B64}"
          : "${CERTIFICATE_PRIVATE_KEY_B64:?missing CERTIFICATE_PRIVATE_KEY_B64}"
          : "${APP_STORE_CONNECT_ISSUER_ID:?missing APP_STORE_CONNECT_ISSUER_ID}"
          : "${APP_STORE_CONNECT_KEY_IDENTIFIER:?missing APP_STORE_CONNECT_KEY_IDENTIFIER}"
          : "${BUNDLE_ID:?missing BUNDLE_ID}"

          # Decode from base64 to files
          echo "$APP_STORE_CONNECT_PRIVATE_KEY_B64" | base64 --decode > asc_key_win.p8
          echo "$CERTIFICATE_PRIVATE_KEY_B64"      | base64 --decode > cert_win.key

          # Strip Windows CRs -> produce clean LF PEMs
          tr -d '\r' < asc_key_win.p8 > asc_key.p8
          tr -d '\r' < cert_win.key  > cert.key

          # Validate headers and size (fail early with clear messages)
          head -2 asc_key.p8; tail -2 asc_key.p8
          head -2 cert.key;   tail -2 cert.key

          grep -qx "-----BEGIN PRIVATE KEY-----"       <(head -1 asc_key.p8) || { echo "asc_key.p8: missing BEGIN PRIVATE KEY"; exit 1; }
          grep -qx "-----END PRIVATE KEY-----"         <(tail -1 asc_key.p8) || { echo "asc_key.p8: missing END PRIVATE KEY";   exit 1; }
          grep -qx "-----BEGIN RSA PRIVATE KEY-----"   <(head -1 cert.key)   || { echo "cert.key:   missing BEGIN RSA PRIVATE KEY"; exit 1; }
          grep -qx "-----END RSA PRIVATE KEY-----"     <(tail -1 cert.key)   || { echo "cert.key:   missing END RSA PRIVATE KEY";   exit 1; }

          P8_BYTES=$(wc -c < asc_key.p8 | tr -d ' ')
          RSA_BYTES=$(wc -c < cert.key | tr -d ' ')
          [ "$P8_BYTES"  -gt 500 ] || { echo "asc_key.p8 too small -> wrong .p8 base64"; exit 1; }
          [ "$RSA_BYTES" -gt 500 ] || { echo "cert.key too small -> wrong RSA base64";  exit 1; }

          # Fetch signing files (creates Apple Distribution cert + provisioning profile)
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$(cat asc_key.p8)" \
            --certificate-key "$(cat cert.key)"

      - name: "Resolve dependencies (CocoaPods)"
        script: |
          if [ -f "Podfile" ]; then
            pod repo update
            pod install
            # If you installed pods, XCODE_PROJECT must be the .xcworkspace
          fi

      - name: "Build and export IPA"
        script: |
          set -euo pipefail
          if [[ "$XCODE_PROJECT" == *.xcworkspace ]]; then
            xcode-project build-ipa \
              --workspace "$XCODE_PROJECT" \
              --scheme "$XCODE_SCHEME" \
              --archive-configuration "Release" \
              --export-method "$EXPORT_METHOD"
          else
            xcode-project build-ipa \
              --project "$XCODE_PROJECT" \
              --scheme "$XCODE_SCHEME" \
              --archive-configuration "Release" \
              --export-method "$EXPORT_METHOD"
          fi

    artifacts:
      - "$CM_EXPORT_DIR/*.ipa"
      - "$CM_EXPORT_DIR/*.dSYM.zip"
      - "$CM_EXPORT_DIR/export-options.plist"
      - "~/Library/Logs/gym/*.log"
