workflows:
  ios_auto_sign:
    name: "iOS • Auto signing via ASC"
    environment:
      xcode: 16.4
      cocoapods: default
      vars:
        # Non-secrets only here
        BUNDLE_ID: "com.yourcompany.yourapp"
        # Use ONE of these: .xcworkspace (Pods) OR .xcodeproj (no Pods)
        XCODE_PROJECT: "YourApp.xcworkspace"   # or "YourApp.xcodeproj"
        XCODE_SCHEME: "YourApp"
        EXPORT_METHOD: "app-store"             # app-store | ad-hoc | development | enterprise

    cache:
      cache_paths:
        - "~/Library/Caches/CocoaPods"
        - "~/Library/Developer/Xcode/DerivedData"

    scripts:
      - name: "Fetch signing files from App Store Connect"
        script: |
          set -euo pipefail
          # These are read from Team → Environment variables
          : "${APP_STORE_CONNECT_ISSUER_ID:?missing}"
          : "${APP_STORE_CONNECT_KEY_IDENTIFIER:?missing}"
          : "${APP_STORE_CONNECT_PRIVATE_KEY:?missing}"
          : "${CERTIFICATE_PRIVATE_KEY:?missing}"

          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create

      - name: "Resolve dependencies (CocoaPods)"
        script: |
          if [ -f "Podfile" ]; then
            pod repo update
            pod install
          fi

      - name: "Debug: show codesign identities and profiles"
        script: |
          security find-identity -v -p codesigning || true
          ls -1 "$HOME/Library/MobileDevice/Provisioning Profiles" || true

      - name: "Build and export IPA"
        script: |
          set -euo pipefail
          if [[ "$XCODE_PROJECT" == *.xcworkspace ]]; then
            xcode-project build-ipa \
              --workspace "$XCODE_PROJECT" \
              --scheme "$XCODE_SCHEME" \
              --archive-configuration "Release" \
              --export-method "$EXPORT_METHOD"
          else
            xcode-project build-ipa \
              --project "$XCODE_PROJECT" \
              --scheme "$XCODE_SCHEME" \
              --archive-configuration "Release" \
              --export-method "$EXPORT_METHOD"
          fi

    artifacts:
      - "$CM_EXPORT_DIR/*.ipa"
      - "$CM_EXPORT_DIR/*.dSYM.zip"
      - "$CM_EXPORT_DIR/export-options.plist"
      - "~/Library/Logs/gym/*.log"

