workflows:
  ios_auto_sign:
    name: "iOS • Auto signing via ASC"
    environment:
      xcode: 16.4
      cocoapods: default
      vars:
        # ASC API key (store real values as Encrypted in UI)
        APP_STORE_CONNECT_ISSUER_ID: "Encrypted(...)"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "Encrypted(...)"
        APP_STORE_CONNECT_PRIVATE_KEY: |-
          -----BEGIN PRIVATE KEY-----
          <your .p8 contents here>
          -----END PRIVATE KEY-----

        # Required for --create (RSA key used to generate the signing cert)
        CERTIFICATE_PRIVATE_KEY: |-
          -----BEGIN RSA PRIVATE KEY-----
          <from `openssl genrsa -out private.key 2048`>
          -----END RSA PRIVATE KEY-----

        # Project settings
        BUNDLE_ID: "com.yourcompany.yourapp"
        # Use ONE of these: .xcworkspace (Pods) OR .xcodeproj (no Pods)
        XCODE_PROJECT: "YourApp.xcworkspace"   # change to "YourApp.xcodeproj" if no CocoaPods
        XCODE_SCHEME: "YourApp"
        EXPORT_METHOD: "app-store"              # app-store | ad-hoc | development | enterprise

    cache:
      cache_paths:
        - "~/Library/Caches/CocoaPods"
        - "~/Library/Developer/Xcode/DerivedData"

    scripts:
      - name: "Fetch signing files from App Store Connect"
        script: |
          set -euo pipefail
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create

      - name: "Resolve dependencies (CocoaPods)"
        script: |
          if [ -f "Podfile" ]; then
            pod repo update
            pod install
          fi

      - name: "Debug: show codesign identities and profiles"
        script: |
          security find-identity -v -p codesigning || true
          ls -1 "$HOME/Library/MobileDevice/Provisioning Profiles" || true

      - name: "Build and export IPA"
        script: |
          set -euo pipefail
          if [[ "$XCODE_PROJECT" == *.xcworkspace ]]; then
            xcode-project build-ipa \
              --workspace "$XCODE_PROJECT" \
              --scheme "$XCODE_SCHEME" \
              --archive-configuration "Release" \
              --export-method "$EXPORT_METHOD"
          else
            xcode-project build-ipa \
              --project "$XCODE_PROJECT" \
              --scheme "$XCODE_SCHEME" \
              --archive-configuration "Release" \
              --export-method "$EXPORT_METHOD"
          fi

    artifacts:
      - "$CM_EXPORT_DIR/*.ipa"
      - "$CM_EXPORT_DIR/*.dSYM.zip"
      - "$CM_EXPORT_DIR/export-options.plist"
      - "~/Library/Logs/gym/*.log"

    # Optional: enable to upload to TestFlight automatically
    # publishing:
    #   app_store_connect:
    #     auth: api_key
    #     key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
    #     issuer_id: $APP_STORE_CONNECT_ISSUER_ID
    #     private_key: $APP_STORE_CONNECT_PRIVATE_KEY
    #     submit_to_testflight: true
    #     beta_groups:
    #       - "Internal Testers"
