workflows:
  ios_capacitor_appstore:
    name: iOS Capacitor App Store (nested app dir)
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      xcode: 16.4
      node: 22
      cocoapods: default
      groups:
        - appstore                        # imports APP_STORE_CONNECT_* from your "appstore" group
      vars:
        APP_DIR: "TeacherType"            # project root inside repo
        XCODE_SCHEME: "App"
        XCODE_WORKSPACE: "TeacherType/ios/App/App.xcworkspace"
        DEVELOPMENT_TEAM: "8598VNYD3C"
        BUNDLE_ID: "com.AbleNest"         # must match TeacherType/capacitor.config.ts

    scripts:
      - name: Install dependencies
        script: |
          set -euo pipefail
          cd "$APP_DIR"
          npm ci

      - name: Build web and sync Capacitor
        script: |
          set -euo pipefail
          cd "$APP_DIR"
          npm run build || true
          npx cap sync ios

      - name: Assert bundle id is com.AbleNest
        script: |
          set -euo pipefail
          grep -R "PRODUCT_BUNDLE_IDENTIFIER" -n "$APP_DIR/ios/App/App.xcodeproj/project.pbxproj"

      - name: CocoaPods
        script: |
          set -euo pipefail
          cd "$APP_DIR/ios/App"
          pod install

      - name: Check App Store Connect secrets
        script: |
          set -euo pipefail
          : "${APP_STORE_CONNECT_PRIVATE_KEY:?APP_STORE_CONNECT_PRIVATE_KEY missing}"
          : "${APP_STORE_CONNECT_KEY_IDENTIFIER:?APP_STORE_CONNECT_KEY_IDENTIFIER missing}"
          : "${APP_STORE_CONNECT_ISSUER_ID:?APP_STORE_CONNECT_ISSUER_ID missing}"
          echo "All App Store Connect secrets are present."

      - name: Prepare signing (fetch profiles via App Store Connect)
        script: |
          set -euo pipefail
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-identifier "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY"
          keychain add-certificates
          xcode-project use-profiles

      - name: Xcode archive (Manual signing with fetched profile)
        script: |
          set -euo pipefail
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -destination "generic/platform=iOS" \
            CODE_SIGN_STYLE=Manual \
            archive

      - name: Create exportOptions.plist
        script: |
          set -euo pipefail
          cat > "$CM_BUILD_DIR/exportOptions.plist" <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0"><dict>
            <key>method</key><string>app-store</string>
            <key>stripSwiftSymbols</key><true/>
            <key>compileBitcode</key><false/>
          </dict></plist>
          PLIST

      - name: Export IPA
        script: |
          set -euo pipefail
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -exportPath "$CM_BUILD_DIR/build" \
            -exportOptionsPlist "$CM_BUILD_DIR/exportOptions.plist"

    artifacts:
      - $CM_BUILD_DIR/build/*.ipa
      - $CM_BUILD_DIR/App.xcarchive

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false
        beta_groups:
          - "Internal Testers"