workflows:
  ios_capacitor_appstore:
    name: iOS Capacitor App Store (nested app dir)
    max_build_duration: 60
    environment:
      xcode: 16.4
      node: 22
      cocoapods: default
      vars:
        APP_DIR: "TeacherType"
        XCODE_SCHEME: "App"
        XCODE_WORKSPACE: "TeacherType/ios/App/App.xcworkspace"
        DEVELOPMENT_TEAM: "8598VNYD3C"
    scripts:
      - name: Install dependencies
        script: |
          cd ""
          npm ci
      - name: Build web and sync Capacitor
        script: |
          cd ""
          npm run build
          npx cap sync ios
      - name: CocoaPods
        script: |
          cd "/ios/App"
          pod repo update
          pod install
      - name: Xcode archive
        script: |
          xcodebuild 
            -workspace "" 
            -scheme "" 
            -configuration Release 
            -archivePath "/App.xcarchive" 
            -destination "generic/platform=iOS" 
            DEVELOPMENT_TEAM="" 
            CODE_SIGN_STYLE=Automatic 
            -allowProvisioningUpdates 
            archive
      - name: Export IPA
        script: |
          # Create exportOptions.plist for App Store/TestFlight
          cat > "/exportOptions.plist" <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>automatic</string>
            <key>stripSwiftSymbols</key><true/>
            <key>uploadSymbols</key><true/>
            <key>compileBitcode</key><false/>
          </dict>
          </plist>
          PLIST

          xcodebuild -exportArchive 
            -archivePath "/App.xcarchive" 
            -exportPath "/build" 
            -exportOptionsPlist "/exportOptions.plist" 
            -allowProvisioningUpdates
    artifacts:
      - build/*.ipa
      - App.xcarchive
    publishing:
      app_store_connect:
        api_key: 
        key_id: 
        issuer_id: 
        submit_to_app_store: false
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
